### ISSUE TITLE
phpunit risky test

### ISSUE THREAD

**Issue by asaliev** [QoboLtd/project-template-wordpress#185] opened 2018-06-14 09:45 UTC
`DotEnvTest::testDotenvExampleFileIsParseable` will yield a phpunit risky test notice when the test is successful.

Output:

```bash
$ vendor/bin/phpunit 
PHPUnit 6.5.8 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.14
Configuration: /obfuscated/phpunit.xml.dist
Error:         No code coverage driver is available

.......RR...                                                      12 / 12 (100%)

Time: 46 ms, Memory: 6.00MB

There were 2 risky tests:

1) Tests\Unit\DotenvTest::testDotenvExampleFileIsParseable with data set ".env.example" ('/obfuscated/', '.env.example')
This test did not perform any assertions

2) Tests\Unit\DotenvTest::testDotenvExampleFileIsParseable with data set ".env" ('/obfuscated/', '.env')
This test did not perform any assertions
```

https://github.com/QoboLtd/project-template-wordpress/blob/b56711066d4b5a70efbdd6af5e7fcb9841cc9a0b/tests/Unit/DotenvTest.php#L40

**Comment by mamchenkov** [comment] 2018-06-15 06:59
@asaliev 

thanks for the report.

At this time, it is unclear how you ended up with the PHPUnit v6.5.8 in the vendor folder.  PHPUnit v6+ dropped support for PHP 5.6 (here are the [Release Notes](https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-6.0.0)) and it requires PHP 7+.  In our `composer.json` file we currently limit all package selection to PHP 5.6 compatible versions, using the platform config.

https://github.com/QoboLtd/project-template-wordpress/blob/master/composer.json#L24

Unless you modified the `composer.json`, PHPUnit 6 should not have been installed.  If that happened, it sounds more like a composer bug to me.

Can you please check if you have any local modifications to the `composer.json` file.

**Comment by asaliev** [comment] 2018-06-15 14:15
> Can you please check if you have any local modifications to the `composer.json` file.

Thanks for pointing that out, I've actually removed the php5.6 constrain due to.. well, reasons.

Seems that phpunit 5.* doesn't activate the risky test check by default.
> Starting with PHPUnit 6, the risky test check for useless tests is active by default. ([source](https://thephp.cc/news/2017/02/migrating-to-phpunit-6))

Looks like `--dont-report-useless-tests` config option is good enough for me.

**Comment by mamchenkov** [comment] 2018-06-16 11:58
@asaliev ,

the platform config in composer makes sure that the versions selected to satisfy requirements, will work on PHP 5.6.  Most of these will also work on PHP 7+.  We are using both, so we set the platform to the lowest value.

We are currently deprecating PHP 5.6 and soon it will be gone and replaced with at least PHP 7.1.  It is safer to leave the composer platform config as it is for now, or you'll find a whole bunch of random issues. :) 

Note that "platform 5.6" is different from "require 5.6".

**Comment by mamchenkov** [comment] 2018-06-16 11:59
Closing, as not a bug. :)

**Closed by mamchenkov** 2018-06-16 11:59 UTC
